# Generated by Django 4.0.1 on 2022-01-19 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_remove_comment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
