# Generated by Django 4.0.1 on 2022-01-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_photo_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
    ]
