# Generated by Django 4.0.1 on 2022-01-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_remove_photo_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
    ]
