# Generated by Django 4.0.1 on 2022-01-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_rename_photo_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='image',
        ),
    ]
